modules:
  - name: runtime
    config:
      "@type": cosmos.app.runtime.v1alpha1.Module
      app_name: SimApp
      begin_blockers: [ capability, distribution, staking, ibc, authz ]
      end_blockers: [ staking ]
      # NOTE: x/fiattokenfactory must be initialized between x/bank and x/genutil
      init_genesis: [ capability, auth, bank, distribution, staking, ibc, fiattokenfactory, genutil, transfer, authz, upgrade ]
      override_store_keys:
        - module_name: auth
          kv_store_key: acc
  - name: auth
    config:
      "@type": cosmos.auth.module.v1.Module
      bech32_prefix: noble
      module_account_permissions:
        - account: fee_collector
        - account: distribution
        - account: bonded_tokens_pool
          permissions: [ burner, staking ]
        - account: not_bonded_tokens_pool
          permissions: [ burner, staking ]
        - account: transfer
          permissions: [ burner, minter ]
        - account: fiat-tokenfactory
          permissions: [ burner, minter ]
  - name: authz
    config:
      "@type": cosmos.authz.module.v1.Module
  - name: bank
    config:
      "@type": cosmos.bank.module.v1.Module
      blocked_module_accounts_override:
        [ auth, distribution, bonded_tokens_pool, not_bonded_tokens_pool ]
  - name: consensus
    config:
      "@type": cosmos.consensus.module.v1.Module
  - name: distribution
    config:
      "@type": cosmos.distribution.module.v1.Module
  - name: genutil
    config:
      "@type": cosmos.genutil.module.v1.Module
  - name: params
    config:
      "@type": cosmos.params.module.v1.Module
  - name: staking
    config:
      "@type": cosmos.staking.module.v1.Module
  - name: tx
    config:
      "@type": cosmos.tx.config.v1.Config
  - name: upgrade
    config:
      "@type": cosmos.upgrade.module.v1.Module

  - name: fiattokenfactory
    config:
      "@type": circle.fiattokenfactory.module.v1.Module
